# Generated by Django 5.1.7 on 2025-04-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_livro_categoria_livro_editora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'autor', 'verbose_name_plural': 'autores'},
        ),
    ]
